### ISSUE TITLE
wfrender with two schedulers in parallel experiences sporadic hangs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wfrog/wfrog#6]
```
wfrender with two schedulers in parallel experiences sporadic hangs. The
configuration which experienced these problems was:

    renderer: !multi
        parallel: true
        renderers:
            meteoclimatic: !scheduler
                period: 600  # in seconds
                renderer: !ftp
                    host: xxxx
                    username: xxxx
                    password: xxxx
                    directory: wfrog
                    renderers:
                        ESIBA0700000107240B.txt: !file
                            path: /tmp/ESIBA0700000107240B.txt
                            renderer: !meteoclimatic
                                id: ESIBA0700000107240B 
            htmlpages1: !scheduler
                period: 900
                renderer: !ftp
                    host: xxxx
                    username: xxxx
                    password: xxxx
                    directory: wfrog
                    renderers:
                        3hours.html: !file
                            path: /tmp/3hours.html
                            renderer: !include
                                path: default/3hours.yaml
                        24hours.html: !file
                            path: /tmp/24hours.html
                            renderer: !include
                                path: default/24hours.yaml
                        30days.html: !file
                            path: /tmp/30days.html
                            renderer: !include
                                path: default/30days.yaml

    So far the solution has been to have a single scheduler. I don't have a
clue on how it hangs or why... 
```

Original issue reported on code.google.com by `jordi.pu...@gmail.com` on 7 Feb 2010 at 8:43
